### ISSUE TITLE
Accept number of hexagons wide and tall

### ISSUE THREAD

**Issue by knitcodemonkey** [knitcodemonkey/hexagon-quilt-map#1]
# Issue

## Current behavior

At the moment, the form accepts hexagons wide and tall, and adjusts the number of hexagons correctly, but the layout only works if you use an even number for width. 

## Desired behavior

Accepts any whole number of hexagons wide and tall.

**Comment by izhuravlev** [comment]
Hey @knitcodemonkey, 
As for the moment when I've opened the app (https://knitcodemonkey.github.io/hexagon-quilt-map/), there is a field for user input to receive hexagons width and height. Do you want the app to scale created hexagons appropriately?

**Comment by knitcodemonkey** [comment]
Currently, the layout only works if you use an even number of hexagons wide. We need to allow it to correctly adapt to odd numbered hexagons.

**Comment by izhuravlev** [comment]
@knitcodemonkey I can try to fix this

**Comment by knitcodemonkey** [comment]
I'm so sorry, @izhuravlev. I didn't notice your request to take this issue until just now. Another good issue might be to add a square shape, not just a hexagon: Story #6.
