### ISSUE TITLE
Include form field selections in localStorage

### ISSUE THREAD

**Issue by knitcodemonkey** [knitcodemonkey/hexagon-quilt-map#14]
# Issue

Currently the current image order for the quilt saves to localStorage, but not any of the form fields. Those are important to maintaining the same quilt you'd previously generated

## Current Behavior

When you refresh page, all form fields revert to their defaults

## Desired Behavior

When you refresh the page, all selections stay as you selected them.

## Step-by-step Instructions to Reproduce Behavior

- Change the height, width, shape of the quilt, and refresh. 
- All form fields revert back to defaults.

**Comment by ballin98** [comment]
Hi, can I work on this issue ?

**Comment by knitcodemonkey** [comment]
@ballin98 Sure! Let me know if you have any questions.
