### ISSUE TITLE
Right Triangles has an odd extra row of disconnected triangles at the bottom

### ISSUE THREAD

**Issue by knitcodemonkey** [knitcodemonkey/hexagon-quilt-map#24]
**Describe the bug**
Number of rows incorrect on right triangles

**Additional context**
In order to show the half hexagons and second half of the right triangles, we are adding an additional row to the row selected, and then cutting off the top half row and bottom half row.

For Right triangles, though, we, at the very least, to always end on an even row, either the number selected or number selected + 1.

Ideally, we'd have twice the number of rows selected, which would always result in an even number. We are passing in the shape to the functions that generate the list of fabrics. We may be able to utilize that section to allow for twice the number of fabrics to be generated based on the shape.

**Comment by izhuravlev** [comment]
I would work on that while we're deciding on the questions in #4
