### ISSUE TITLE
Allow new Square shape

### ISSUE THREAD

**Issue by knitcodemonkey** [knitcodemonkey/hexagon-quilt-map#6]
# Issue

## Current Behavior

Hexagon is the only shape

## Desired Behavior

Add a Square shape:

[ ] Add a form select to include Square
[ ] Create a Square component
[ ] Allow prop to load either the Hexagon or Square layout
[ ] Default to Hexagon

**Comment by izhuravlev** [comment]
I can take a look at it

**Comment by izhuravlev** [comment]
@knitcodemonkey do you want them to be in form of squares (top and bottom are parallel to the horizon) or like rhombuses (squares turned 45 degrees)?

**Comment by knitcodemonkey** [comment]
Actual squares with the top and bottom perpendicular to the left and right, please. 

Example of an actual quilt:

![image](https://user-images.githubusercontent.com/1584489/67802186-472d7580-fa50-11e9-9e0b-0b5860598bfc.png)

**Comment by izhuravlev** [comment]
@knitcodemonkey on it!
